config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :blueprints

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blueprint.rb
class Blueprint < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blueprints_controller.rb
class BlueprintsController < ApplicationController
  def index
    @blueprints = Blueprint.all
  end

  def show
    @blueprint = Blueprint.find(params[:id])
  end

  def new
    @blueprint = Blueprint.new
  end

  def edit
    @blueprint = Blueprint.find(params[:id])
  end

  def create
    @blueprint = Blueprint.new(blueprint_params)

    if @blueprint.save
      redirect_to @blueprint
    else
      render 'new'
    end
  end

  def update
    @blueprint = Blueprint.find(params[:id])

    if @blueprint.update(blueprint_params)
      redirect_to @blueprint
    else
      render 'edit'
    end
  end

  def destroy
    @blueprint = Blueprint.find(params[:id])
    @blueprint.destroy

    redirect_to blueprints_path
  end

  private
  def blueprint_params
    params.require(:blueprint).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blueprints_helper.rb
module BlueprintsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blueprints/_form.html.erb
<%= form_for @blueprint do |f| %>
  <% if @blueprint.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blueprint.errors.count, 'error') %> found:
      </h2>
      <ul>
        <% @blueprint.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/blueprints/edit.html.erb
<h1>Change your blueprint</h1>

<%= render 'form' %>

<%= link_to 'Back', blueprints_path %>

app/views/blueprints/index.html.erb
<h1>This is a list of all the cool blueprints!</h1>

<%= link_to 'New blueprint', new_blueprint_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>

  <% @blueprints.each do |blueprint| %>
    <tr>
      <td><%= blueprint.title %></td>
      <td><%= blueprint.description %></td>
      <td><%= link_to 'Show', blueprint_path(blueprint) %></td>
      <td><%= link_to 'Edit', edit_blueprint_path(blueprint) %></td>
      <td><%= link_to 'Delete', blueprint_path(blueprint),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>

app/views/blueprints/new.html.erb
<h1>Create a new blueprint</h1>

<%= render 'form' %>

<%= link_to 'Back', blueprints_path %>

app/views/blueprints/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blueprint.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blueprint.description %>
</p>

<%= link_to 'Edit', edit_blueprint_path(@blueprint) %>
<%= link_to 'Back to blueprints', blueprints_path %>

app/views/home/index.html.erb
<h1>FactorioDB</h1>

<%= link_to 'View Blueprints', controller: 'blueprints' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Factoriodb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>